#ifndef RigelDriverConstants_h
#define RigelDriverConstants_h
#include "WConstants.h"

// RigelDriver Constants
#define SERVO_CATCH_UP_DELAY 		15

#define RIGHT_ANGLE_CONSTANT		200

#define SERVO_PIN_LEFT_FRONT 		8
#define SERVO_PIN_RIGHT_FRONT 	9
#define SERVO_PIN_LEFT_BACK 		10
#define SERVO_PIN_RIGHT_BACK 		11

#define FULL_SPEED_FORWARD_LEFT_FRONT 		180
#define FULL_SPEED_FORWARD_RIGHT_FRONT 		0
#define FULL_SPEED_FORWARD_LEFT_BACK 			180
#define FULL_SPEED_FORWARD_RIGHT_BACK 		0

#define FULL_SPEED_BACKWARDS_LEFT_FRONT 	0
#define FULL_SPEED_BACKWARDS_RIGHT_FRONT 	180
#define FULL_SPEED_BACKWARDS_LEFT_BACK 		0
#define FULL_SPEED_BACKWARDS_RIGHT_BACK 	180

#define HALF_SPEED_FORWARD_LEFT_FRONT 		105
#define HALF_SPEED_FORWARD_RIGHT_FRONT 		75
#define HALF_SPEED_FORWARD_LEFT_BACK 			105
#define HALF_SPEED_FORWARD_RIGHT_BACK 		75

#define HALF_SPEED_BACKWARDS_LEFT_FRONT 	75
#define HALF_SPEED_BACKWARDS_RIGHT_FRONT 	105
#define HALF_SPEED_BACKWARDS_LEFT_BACK 		75
#define HALF_SPEED_BACKWARDS_RIGHT_BACK 	105

#define SERVO_HALT 												90


#endif
